export { default as Home } from './Home';
export { default as About } from './About';
export { default as Contact } from './Contact';
export { default as Pricing } from './Pricing';
export { default as CreatePassword } from './CreatePassword';
export { default as VerifyPassword } from './VerifyPassword';
export { default as ForgetPassword } from './ForgetPassword';
export { default as FAQS } from './FAQS';
export { default as SignIn } from './SignIn';
